/* API-driven evidence display. It never creates labels, predictions, or linkages. */
(() => {
  "use strict";
  const $ = id => document.getElementById(id);
  const safe = value => { const node = document.createElement("span"); node.textContent = value ?? "—"; return node.innerHTML; };
  const api = async path => { const response = await fetch(path); if (!response.ok) throw Error(`HTTP ${response.status}`); return response.json(); };
  const fmt = (value, decimals = 1) => value === "" || value == null ? "—" : Number(value).toFixed(decimals);
  let map, eventLayer, boundaryLayer, allEvents = [];

  function initMap() {
    map = L.map("map").setView([11.41, 76.69], 10);
    L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", { maxZoom: 18, attribution: "© OpenStreetMap contributors" }).addTo(map);
    eventLayer = L.layerGroup().addTo(map); boundaryLayer = L.layerGroup().addTo(map);
    $("toggle-events").onchange = event => event.target.checked ? map.addLayer(eventLayer) : map.removeLayer(eventLayer);
    $("toggle-boundaries").onchange = event => event.target.checked ? map.addLayer(boundaryLayer) : map.removeLayer(boundaryLayer);
  }

  async function loadStatus() { const status = await api("/api/status"); $("model-status").textContent = status.ml_status.replace("_", " "); $("model-reason").textContent = status.reason; }
  async function loadVillages() { const data = await api("/api/villages?limit=12"); $("village-count").textContent = data.record_count; $("village-summary").lastElementChild.textContent = `${data.record_count} Village Master records; ${data.exact_spatial_matches} exact LGD-code KMZ matches. ${data.village_master_only} Village Master-only and ${data.kmz_only} KMZ-only records remain unmatched.`; $("village-table").innerHTML = data.records.map(row => `<tr><td>${safe(row.village_name_en)}</td><td>${safe(row.taluk_name_en)}</td><td>${safe(row.village_lgd_code)}</td></tr>`).join(""); }
  async function loadEvents() { const data = await api("/api/events"); allEvents = data.records; $("event-count").textContent = data.record_count; $("event-total").textContent = data.record_count; $("event-dates").innerHTML = Object.entries(data.date_categories).map(([key, value]) => `<div><dt>${safe(key.replace("_", " "))}</dt><dd>${value}</dd></div>`).join(""); $("events-table").innerHTML = data.records.slice(0, 10).map(row => `<tr><td>${safe(row.location_description)}</td><td>${safe(row.history_raw)}</td><td>${safe(row.material_involved)}</td><td>${safe(row.movement_type)}</td></tr>`).join(""); data.records.forEach(row => { const latitude = Number(row.latitude), longitude = Number(row.longitude); if (Number.isFinite(latitude) && Number.isFinite(longitude)) L.circleMarker([latitude, longitude], { radius: 3, color: "#fff", weight: 1, fillColor: "#4f6570", fillOpacity: .75 }).bindPopup(`<strong>GSI/NLFC inventory evidence</strong><br>${safe(row.location_description)}<br>History: ${safe(row.history_raw)}`).addTo(eventLayer); }); }
  async function loadTerrain() { const data = await api("/api/terrain"); $("terrain-cards").innerHTML = data.records.map(row => `<article class="terrain-card"><span class="badge demo">DEMO</span><h3>${safe(row.settlement_name)}</h3><div class="terrain-values"><div><strong>${fmt(row.elevation_m, 0)} m</strong><span>Elevation</span></div><div><strong>${fmt(row.slope_deg)}°</strong><span>Slope</span></div></div></article>`).join(""); }
  async function loadRain() { const year = $("rain-year").value, data = await api(`/api/rainfall?year=${year}`), ids = [...new Set(data.records.map(row => row.settlement_id))], select = $("rain-place"); if (!select.options.length) select.innerHTML = ids.map(id => { const row = data.records.find(item => item.settlement_id === id); return `<option value="${safe(id)}">${safe(row.settlement_name)}</option>`; }).join(""); const rows = data.records.filter(row => row.settlement_id === select.value).sort((a, b) => b.date.localeCompare(a.date)); $("rain-table").innerHTML = rows.slice(0, 14).map(row => `<tr><td>${row.date}</td><td>${fmt(row.rainfall_1d_mm)}</td><td>${fmt(row.rainfall_3d_mm)}</td><td>${fmt(row.rainfall_7d_mm)}</td></tr>`).join(""); $("rain-reading").textContent = `${data.records.length} validated ${year} feature rows; no imputation.`; $("rain-status").textContent = "Showing latest 14 dates for the selected DEMO location."; }
  async function loadDdmp() { const data = await api("/api/ddmp"), counts = data.manifest.explicit_record_counts; $("ddmp-cards").innerHTML = `<article><span class="badge real">REAL</span><h3>${counts.proposed_automatic_rainguage_stations} proposed ARG stations</h3><p>DDMP Table 2.6; commissioning is not inferred.</p></article><article><span class="badge real">REAL</span><h3>${counts.automatic_weather_stations} AWS records</h3><p>Source-listed stations; no sensor coverage assumed.</p></article><article><span class="badge real">REAL</span><h3>${counts.gsi_august_2019_landslide_records} GSI August-2019 records</h3><p>Documentary evidence; not merged with the inventory.</p></article>`; $("ddmp-table").innerHTML = data.vulnerability_summary.map(row => `<tr><td>${safe(row.taluk)}</td><td>${safe(row["Very Highly Vulnerable"])}</td><td>${safe(row["Highly Vulnerable"])}</td><td>${safe(row["Medium Vulnerable"])}</td><td>${safe(row["Low Vulnerable"])}</td><td>${safe(row.Total)}</td></tr>`).join(""); }
  async function loadExperimentalIndex() {
    const data = await api("/api/experimental-hazard-index"), select = $("experimental-village"), rows = [...data.records].sort((a, b) => a.village_name_en.localeCompare(b.village_name_en));
    select.innerHTML = rows.map(row => `<option value="${safe(row.village_lgd_code)}">${safe(row.village_name_en)} (${safe(row.village_lgd_code)})</option>`).join("");
    const render = () => {
      const row = rows.find(item => item.village_lgd_code === select.value); if (!row) return;
      $("experimental-reading").textContent = `${data.record_count} validated villages; fixed Phase 8 method.`;
      $("experimental-detail").innerHTML = `<article><strong>${fmt(row.terrain_component, 3)}</strong><span>Terrain component</span></article><article><strong>${fmt(row.rainfall_7d_p95_minmax, 3)}</strong><span>Historical rainfall component</span></article><article><strong>${fmt(row.conditional_event_evidence_minmax, 3)}</strong><span>Conditional event-evidence component</span></article><article><strong>${fmt(row.experimental_hazard_index_0_100, 1)}</strong><span>Experimental index (0–100)</span></article>`;
      $("experimental-provenance").innerHTML = [["Rainfall feature source", row.rainfall_feature_source], ["Terrain feature source", row.terrain_feature_source], ["Event evidence source", row.event_evidence_source], ["Event evidence qualification", row.event_evidence_qualification], ["Index method", row.index_method_version]].map(([key, value]) => `<div><dt>${safe(key)}</dt><dd>${safe(value)}</dd></div>`).join("");
    };
    $("experimental-table").innerHTML = rows.map(row => `<tr><td>${safe(row.village_name_en)}</td><td>${safe(row.taluk_lgd_code)}</td><td>${fmt(row.experimental_hazard_index_0_100, 1)}</td></tr>`).join("");
    select.onchange = render; render();
  }
  async function loadBoundaries() { try { const response = await fetch("/data/raw/admin/vb_soi_tn.kmz"), zip = await JSZip.loadAsync(await response.arrayBuffer()), file = Object.values(zip.files).find(item => /\.kml$/i.test(item.name)), xml = new DOMParser().parseFromString(await file.async("text"), "application/xml"); let added = 0; [...xml.querySelectorAll("Placemark")].filter(place => /nilgiri/i.test(place.textContent)).forEach(place => place.querySelectorAll("Polygon outerBoundaryIs LinearRing coordinates").forEach(node => { const points = node.textContent.trim().split(/\s+/).map(value => value.split(",").map(Number)).filter(value => Number.isFinite(value[0]) && Number.isFinite(value[1])).map(value => [value[1], value[0]]); if (points.length > 2) { L.polygon(points, { color: "#146d89", weight: 1, fillOpacity: .06 }).addTo(boundaryLayer); added++; } })); $("map-status").textContent = `${allEvents.length} independent inventory points and ${added} Nilgiris KMZ polygon components loaded. No event-to-village linkage implied.`; } catch (error) { $("map-status").textContent = `Inventory points loaded; KMZ layer unavailable (${error.message}).`; } }
  async function start() { try { initMap(); await Promise.all([loadStatus(), loadVillages(), loadEvents(), loadTerrain(), loadDdmp(), loadExperimentalIndex()]); await loadRain(); $("rain-year").onchange = () => { $("rain-place").innerHTML = ""; loadRain(); }; $("rain-place").onchange = loadRain; await loadBoundaries(); } catch (error) { console.error(error); $("model-reason").textContent = `Dashboard data could not load: ${error.message}`; } }
  start();
})();
