/* API-driven evidence display. It never creates labels, scores, or linkages. */
(() => {
  "use strict";
  const $ = id => document.getElementById(id);
  const safe = value => { const node = document.createElement("span"); node.textContent = value ?? "—"; return node.innerHTML; };
  const api = async path => { const r = await fetch(path); if (!r.ok) throw Error(`HTTP ${r.status}`); return r.json(); };
  const fmt = (value, decimals = 1) => value === "" || value == null ? "—" : Number(value).toFixed(decimals);
  let map, eventLayer, boundaryLayer, allEvents = [];

  function initMap() {
    map = L.map("map").setView([11.41, 76.69], 10);
    L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", { maxZoom: 18, attribution: "© OpenStreetMap contributors" }).addTo(map);
    eventLayer = L.layerGroup().addTo(map); boundaryLayer = L.layerGroup().addTo(map);
    $("toggle-events").onchange = e => e.target.checked ? map.addLayer(eventLayer) : map.removeLayer(eventLayer);
    $("toggle-boundaries").onchange = e => e.target.checked ? map.addLayer(boundaryLayer) : map.removeLayer(boundaryLayer);
  }

  async function loadStatus() { const s = await api("/api/status"); $("model-status").textContent = s.ml_status.replace("_", " "); $("model-reason").textContent = s.reason; }
  async function loadVillages() { const d = await api("/api/villages?limit=12"); $("village-count").textContent = d.record_count; $("village-summary").lastElementChild.textContent = `${d.record_count} Village Master records; ${d.exact_spatial_matches} exact LGD-code KMZ matches. ${d.village_master_only} Village Master-only and ${d.kmz_only} KMZ-only records remain unmatched.`; $("village-table").innerHTML = d.records.map(r => `<tr><td>${safe(r.village_name_en)}</td><td>${safe(r.taluk_name_en)}</td><td>${safe(r.village_lgd_code)}</td></tr>`).join(""); }
  async function loadEvents() { const d = await api("/api/events"); allEvents = d.records; $("event-count").textContent = d.record_count; $("event-total").textContent = d.record_count; $("event-dates").innerHTML = Object.entries(d.date_categories).map(([k,v]) => `<div><dt>${safe(k.replace("_", " "))}</dt><dd>${v}</dd></div>`).join(""); $("events-table").innerHTML = d.records.slice(0,10).map(r => `<tr><td>${safe(r.location_description)}</td><td>${safe(r.history_raw)}</td><td>${safe(r.material_involved)}</td><td>${safe(r.movement_type)}</td></tr>`).join(""); d.records.forEach(r => { const lat=Number(r.latitude), lng=Number(r.longitude); if (Number.isFinite(lat) && Number.isFinite(lng)) L.circleMarker([lat,lng], {radius:3, color:"#fff", weight:1, fillColor:"#4f6570", fillOpacity:.75}).bindPopup(`<strong>GSI/NLFC inventory evidence</strong><br>${safe(r.location_description)}<br>History: ${safe(r.history_raw)}`).addTo(eventLayer); }); }
  async function loadTerrain() { const d = await api("/api/terrain"); $("terrain-cards").innerHTML = d.records.map(r => `<article class="terrain-card"><span class="badge demo">DEMO</span><h3>${safe(r.settlement_name)}</h3><div class="terrain-values"><div><strong>${fmt(r.elevation_m,0)} m</strong><span>Elevation</span></div><div><strong>${fmt(r.slope_deg)}°</strong><span>Slope</span></div></div></article>`).join(""); }
  async function loadRain() { const year = $("rain-year").value, d = await api(`/api/rainfall?year=${year}`), ids = [...new Set(d.records.map(r=>r.settlement_id))], select=$("rain-place"); if (!select.options.length) select.innerHTML = ids.map(id => { const r=d.records.find(x=>x.settlement_id===id); return `<option value="${safe(id)}">${safe(r.settlement_name)}</option>`; }).join(""); const rows=d.records.filter(r=>r.settlement_id===select.value).sort((a,b)=>b.date.localeCompare(a.date)); $("rain-table").innerHTML=rows.slice(0,14).map(r=>`<tr><td>${r.date}</td><td>${fmt(r.rainfall_1d_mm)}</td><td>${fmt(r.rainfall_3d_mm)}</td><td>${fmt(r.rainfall_7d_mm)}</td></tr>`).join(""); $("rain-reading").textContent=`${d.records.length} validated ${year} feature rows; no imputation.`; $("rain-status").textContent="Showing latest 14 dates for the selected DEMO location."; }
  async function loadDdmp() { const d = await api("/api/ddmp"), c=d.manifest.explicit_record_counts; $("ddmp-cards").innerHTML=`<article><span class="badge real">REAL</span><h3>${c.proposed_automatic_rainguage_stations} proposed ARG stations</h3><p>DDMP Table 2.6; commissioning is not inferred.</p></article><article><span class="badge real">REAL</span><h3>${c.automatic_weather_stations} AWS records</h3><p>Source-listed stations; no sensor coverage assumed.</p></article><article><span class="badge real">REAL</span><h3>${c.gsi_august_2019_landslide_records} GSI August-2019 records</h3><p>Documentary evidence; not merged with the inventory.</p></article>`; $("ddmp-table").innerHTML=d.vulnerability_summary.map(r=>`<tr><td>${safe(r.taluk)}</td><td>${safe(r["Very Highly Vulnerable"])}</td><td>${safe(r["Highly Vulnerable"])}</td><td>${safe(r["Medium Vulnerable"])}</td><td>${safe(r["Low Vulnerable"])}</td><td>${safe(r.Total)}</td></tr>`).join(""); }
  async function loadBoundaries() { try { const r=await fetch("/data/raw/admin/vb_soi_tn.kmz"), zip=await JSZip.loadAsync(await r.arrayBuffer()), file=Object.values(zip.files).find(f=>/\.kml$/i.test(f.name)), xml=new DOMParser().parseFromString(await file.async("text"),"application/xml"); let added=0; [...xml.querySelectorAll("Placemark")].filter(p=>/nilgiri/i.test(p.textContent)).forEach(p=>p.querySelectorAll("Polygon outerBoundaryIs LinearRing coordinates").forEach(n=>{const pts=n.textContent.trim().split(/\s+/).map(x=>x.split(",").map(Number)).filter(x=>Number.isFinite(x[0])&&Number.isFinite(x[1])).map(x=>[x[1],x[0]]);if(pts.length>2){L.polygon(pts,{color:"#146d89",weight:1,fillOpacity:.06}).addTo(boundaryLayer);added++;}})); $("map-status").textContent=`${allEvents.length} independent inventory points and ${added} Nilgiris KMZ polygon components loaded. No event-to-village linkage implied.`; } catch(e) { $("map-status").textContent=`Inventory points loaded; KMZ layer unavailable (${e.message}).`; } }
  async function start() { try { initMap(); await Promise.all([loadStatus(),loadVillages(),loadEvents(),loadTerrain(),loadDdmp()]); await loadRain(); $("rain-year").onchange=()=>{ $("rain-place").innerHTML=""; loadRain(); }; $("rain-place").onchange=loadRain; await loadBoundaries(); } catch(e) { console.error(e); $("model-reason").textContent=`Dashboard data could not load: ${e.message}`; } }
  start();
})();
